config/routes.rb
Rails.application.routes.draw do

  resources :semesters
  resources :courses

  root 'courses#index'

end

app/models/course.rb
class Course < ActiveRecord::Base
end

app/models/semester.rb
class Semester < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
      @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
      @course = Course.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(courses_params)
    if @course.save
      redirect_to @course
    else
      render 'new'
    end

  end

  def update
    @course = Course.find(params[:id])
    if @course.update(courses_params)
      redirect_to @course
    else
      render 'edit'
    end

  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to courses_path

  end
  private

    def courses_params
      params.require(:course).permit(:title,:description,:credit)
    end


end

app/controllers/semesters_controller.rb
class SemestersController < ApplicationController
  before_action :set_semester, only: [:show, :edit, :update, :destroy]

  # GET /semesters
  # GET /semesters.json
  def index
    @semesters = Semester.all
  end

  # GET /semesters/1
  # GET /semesters/1.json
  def show
  end

  # GET /semesters/new
  def new
    @semester = Semester.new
  end

  # GET /semesters/1/edit
  def edit
  end

  # POST /semesters
  # POST /semesters.json
  def create
    @semester = Semester.new(semester_params)

    respond_to do |format|
      if @semester.save
        format.html { redirect_to @semester, notice: 'Semester was successfully created.' }
        format.json { render :show, status: :created, location: @semester }
      else
        format.html { render :new }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /semesters/1
  # PATCH/PUT /semesters/1.json
  def update
    respond_to do |format|
      if @semester.update(semester_params)
        format.html { redirect_to @semester, notice: 'Semester was successfully updated.' }
        format.json { render :show, status: :ok, location: @semester }
      else
        format.html { render :edit }
        format.json { render json: @semester.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /semesters/1
  # DELETE /semesters/1.json
  def destroy
    @semester.destroy
    respond_to do |format|
      format.html { redirect_to semesters_url, notice: 'Semester was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_semester
      @semester = Semester.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def semester_params
      params.require(:semester).permit(:name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/semesters_helper.rb
module SemestersHelper
end

app/views/courses/_form.html.erb
<%= form_for (@course) do |f| %>

    <% if @course.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@course.errors.count, "error") %> prohibited this course from being saved:</h2>

          <ul>
            <% @course.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :title, class: 'col-lg-2 control-label'  %><br>
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :description,class: 'col-lg-2 control-label'  %><br>
      <%= f.text_field :description, class: 'form-control' %>
    </div>
    <div class="field">
      <%= f.label :credit,class: 'col-lg-2 control-label'  %><br>
      <%= f.number_field :credit , class: 'form-control' %>
    </div>
    <div class="actions">
      <%= f.submit "Add Course", class: "btn btn-primary" %>
    </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Courses</h1>

<table class="table table-striped  table-hover">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Credit</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @courses.each do |course| %>
      <tr>
        <td><%= course.title %></td>
        <td><%= course.description %></td>
        <td><%= course.credit %></td>
        <td><%= link_to 'Show', course , class: 'btn btn-mini btn-info'  %></td>
        <td><%= link_to 'Edit', edit_course_path(course), class: 'btn btn-mini btn-warning'  %></td>
        <td><%= link_to 'Destroy', course, method: :delete,class: 'btn btn-mini btn-danger' , data: { confirm: 'Are you sure?' } %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Credit:</strong>
  <%= @course.credit %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Finalv1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <ul class = "nav nav-tabs">
    <li> <%= link_to "Home", root_path %> </li>
    <li> <%= link_to "Sign in", root_path %> </li>
    <li> <%= link_to "Sign out", root_path %> </li>
    <li> <%= link_to "New course", new_course_path %> </li>

  </ul>

  <%= yield %>

</div>



</body>
</html>

app/views/semesters/_form.html.erb
<%= form_for(@semester) do |f| %>
  <% if @semester.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@semester.errors.count, "error") %> prohibited this semester from being saved:</h2>

      <ul>
      <% @semester.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, class: 'col-lg-2 control-label'  %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :status, class: 'control-label'  %><br>
    <%= f.select(:status, ["current","Coming Soon"], {}, { :class => 'btn btn-default dropdown-toggle' }) %>
  </div>
  <div class="actions">
    <%= f.submit "Add", class: "btn btn-primary"%>
  </div>
<% end %>

app/views/semesters/edit.html.erb
<h1>Editing Semester</h1>

<%= render 'form' %>

<%= link_to 'Show', @semester %> |
<%= link_to 'Back', semesters_path %>

app/views/semesters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Semesters</h1>

<table class="table table-striped  table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @semesters.each do |semester| %>
      <tr>
        <td><%= semester.name %></td>
        <td><%= semester.status %></td>
        <td><%= link_to 'Show', semester, class: 'btn btn-mini btn-info' %></td>
        <td><%= link_to 'Edit', edit_semester_path(semester), class: 'btn btn-mini btn-warning' %></td>
        <td><%= link_to 'Destroy', semester, method: :delete,class: 'btn btn-mini btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Semester', new_semester_path %>

app/views/semesters/new.html.erb
<h1>New Semester</h1>

<%= render 'form' %>

<%= link_to 'Back', semesters_path %>

app/views/semesters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @semester.name %>
</p>

<p>
  <strong>Status:</strong>
  <%= @semester.status %>
</p>

<%= link_to 'Edit', edit_semester_path(@semester) %> |
<%= link_to 'Back', semesters_path %>